Feature/rocket badges
Bupilipili/Space-Travelers-Hub pull request #35
Opened 2023-08-30 09:32 UTC by Bupilipili

### In this branch

- Rockets show a "Reserved" badge and "Cancel reservation" button instead of the default "Reserve rocket" (as per design)

2023-08-30 11:53 UTC, Bhekisile commented on src/components/Rockets.js
> +                  <button
Please fix the eslint error attached.
![Screenshot (34)](https://github.com/Bupilipili/Space-Travelers-Hub/assets/111288560/bb8a20de-e7ba-4d84-b626-c278ac5b74a7)

2023-08-30 11:55 UTC, Bhekisile commented on src/redux/rockets/RocketSlice.js
> +      );
Same here.
![Screenshot (34)](https://github.com/Bupilipili/Space-Travelers-Hub/assets/111288560/041d0580-95da-47e8-be3d-94dcc8f4ed83)

2023-08-30 11:58 UTC, Bhekisile requested changes
Hi @Bupilipili,

Good job so far!
There are some issues that you still need to work on but you are almost there!
<img src="https://media2.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

2023-08-30 12:02 UTC, Bupilipili commented on src/redux/rockets/RocketSlice.js
> +      );
Thanks for the review, 
But you see all the Linter checks have passed.

2023-08-31 10:50 UTC, Bhekisile requested changes
Hi @Bupilipili,

Good job so far!
There are some issues that you still need to work on but you are almost there!

2023-08-31 10:50 UTC, Bhekisile commented on src/redux/rockets/RocketSlice.js
> +      return state.map((rocket) => (rocket.id !== rocketId ? rocket : { ...rocket, reserved: false }));
I can't open your app, please fix for UX.
![Screenshot (40)](https://github.com/Bupilipili/Space-Travelers-Hub/assets/111288560/7a3def0a-f827-430e-8387-cf52a35dc108)

2023-08-31 10:58 UTC, Bupilipili commented on src/redux/rockets/RocketSlice.js
> +      return state.map((rocket) => (rocket.id !== rocketId ? rocket : { ...rocket, reserved: false }));
Done, try again.

2023-08-31 10:58 UTC, Bupilipili commented on src/redux/rockets/RocketSlice.js
> +      return state.map((rocket) => (rocket.id !== rocketId ? rocket : { ...rocket, reserved: false }));
Done 👍

2023-08-31 15:21 UTC, Bhekisile approved these changes
Hi @Bupilipili,

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

<img src="https://media0.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

2023-08-31 15:50 UTC, merged